# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main


stages:
  - stage: "Build stage"
    displayName: "build state"
    jobs:
      - job: 
        displayName: "build job"
        pool: Default
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean install'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false

          
  - stage: "dev"
    displayName: "dev state"
    jobs:
      - job: "deploy"
        pool: Default
        steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'specific'
            itemPattern: 'drop/**'
            downloadPath: '$(System.ArtifactsDirectory)'
         